# tcb_wings_platform_reconfiguration_1.yaml
---
testcaseBlueprintId: 'wings_platform_reconfiguration_1'
version: '1.0'
name: 'TcB Wings Platform Reconfiguration'
description: ''
script: '### Code ###'
userParameters:
  transmission_frequency: '$$transmission_frequency'
  packet_size: '$$packet_size'
  number_of_nodes: '$$number_of_nodes'
infrastructureParameters:
  ns.nsd_id.vnf.vnfd_id.cp.cpId1.idAddr: '$$varX'
